import Head from 'next/head';
import Avatar from "../components/Avatar";
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline"
import Image from "next/image"
import Footer from '../components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';
import { signIn, signOut, useSession } from 'next-auth/client';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const [session] = useSession();
  const submit = (e) => {
    e.preventDefault();

    const term = searchInputRef.current.value;

    if(!term) return;

    

    router.push(`/search?term=${term}`);
}

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google_2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
      <div className=" flex space-x-4 items-center">
        <p className="link">About</p>
        <p className="link">Store</p>
      </div>

      <div className="flex space-x-4 items-center">
        <p className="link">Gmail</p>
        <p className="link">Image</p>

        <ViewGridIcon className="h-10 w-10 p-2 hover:bg-gray-100 rounded-full cursor-pointer"/>
        {/* <Avatar className="" url="https://images.unsplash.com/photo-1604426633861-11b2faead63c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZmFjZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=60"/> */}
        <div className="" onClick={!session? signIn : signOut}>
          {session ? <Image 
          src={session.user.image}
          height={40}
          width={40}
          className="rounded-full cursor-pointer"
          /> : <button className=" bg-gray-300 p-2 rounded-lg text-gray-600 hover:underline">Sign In</button>}
          
        </div>
      </div>
      </header>

      {/* body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image src="https://th.bing.com/th/id/R.68069f69f0afa847ac6948f766fe904b?rik=4EYoiK%2fkgmzPzw&riu=http%3a%2f%2fwww.google.com%2flogos%2fdoodles%2f2018%2fsri-lanka-national-day-2018-6344453324275712-2xa.gif&ehk=UeV59dQZaiPPzWqcpOKkeNXYugw4TSZzJFGr5QbEvj0%3d&risl=&pid=ImgRaw" height={100} width={300}/>

        <div className=" flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500 cursor-pointer"/>
          <input ref={searchInputRef} type="text" className=" flex-grow focus:outline-none"/>
          <MicrophoneIcon className="h-5 text-gray-500 cursor-pointer"/>
        </div>

        <div className="flex flex-col w-1/2 space-y-2 mt-8 justify-center sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={submit} className="btn"> Google Search </button>
          <button onClick={submit} className="btn"> I'm Feeling Lucky </button>
        </div>
      </form>

      {/* footer */}
      <Footer/>
      
    </div>
  )
}
